package me.cortex.voxy.common.storage.postgres;

import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import me.cortex.voxy.common.storage.StorageBackend;
import me.cortex.voxy.common.storage.config.ConfigBuildCtx;
import me.cortex.voxy.common.storage.config.StorageConfig;
import me.cortex.voxy.common.storage.rocksdb.RocksDBStorageBackend;
import me.cortex.voxy.common.util.MemoryBuffer;

import java.io.ByteArrayInputStream;
import java.nio.ByteBuffer;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.function.LongConsumer;

public class PostgreSQLStorageBackend extends StorageBackend {
    private static final Map<String, PostgreSQLConnectionPool> connectionPoolByDatabaseUrl = new HashMap<>();
    private final PostgreSQLConnectionPool connectionPool;
    private final int levelId;

    public PostgreSQLStorageBackend(String levelName, String databaseUrl, int maxConnections) {
        synchronized (connectionPoolByDatabaseUrl) {
            connectionPool = connectionPoolByDatabaseUrl.computeIfAbsent(
                    databaseUrl,
                    url -> new PostgreSQLConnectionPool(url, maxConnections)
            );
        }

        connectionPool.withConnection(connection -> {
            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("""
                        create table if not exists level (
                            key bigint primary key generated by default as identity,
                            name text not null unique
                        )
                        """);

                statement.executeUpdate("""
                        create table if not exists section (
                            levelId int,
                            key bigint,
                            data bytea,
                            primary key (levelId, key)
                        )
                        """);

                statement.executeUpdate("""
                        create table if not exists mapping (
                            levelId int,
                            key int,
                            data bytea,
                            primary key (levelId, key)
                        )
                        """);
            }
        });

        // ugh, this is annoying.
        // There really should be a better way of upserting a value while returning a different generated value from it.
        // this assumes that levels are not removed (if they were this would create a race condition).
        this.levelId = connectionPool.withConnection(connection -> {
            try (PreparedStatement preparedStatement = connection.prepareStatement("insert into level (name) values (?) on conflict (name) do nothing returning key")) {
                preparedStatement.setString(1, levelName);
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    if (resultSet.next())
                        return resultSet.getInt("key");
                }
            }

            try (PreparedStatement preparedStatement = connection.prepareStatement("select key from level where name = ?")) {
                preparedStatement.setString(1, levelName);
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    if (!resultSet.next())
                        throw new RuntimeException("tried to create level but it already existed, tried to get the level's id but it doesn't exist");

                    return resultSet.getInt("key");
                }
            }
        });
    }

    @Override
    public void iterateStoredSectionPositions(LongConsumer consumer) {
        connectionPool.withConnection(connection -> {
            try (PreparedStatement preparedStatement = connection.prepareStatement("select key from section")) {
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    while (resultSet.next())
                        consumer.accept(resultSet.getLong("key"));
                }
            }
        });
    }

    @Override
    public MemoryBuffer getSectionData(long key, MemoryBuffer scratch) {
        return connectionPool.withConnection(connection -> {
            try (PreparedStatement preparedStatement = connection.prepareStatement(
                    "select data from section where key = ?"
            )) {
                preparedStatement.setLong(1, key);
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    if (!resultSet.next())
                        return null;

                    return resultSet.getBinaryStream("data");
                }
            }
        })
    }

    @Override
    public void setSectionData(long key, MemoryBuffer data) {
        connectionPool.withConnection(connection -> {
            try (PreparedStatement preparedStatement = connection.prepareStatement(
                    "insert into section (key, data) values (?, ?) on conflict (key) do update set data = excluded.data"
            )) {
                preparedStatement.setLong(1, key);
                preparedStatement.setBinaryStream(2, data);
            }
        });
    }

    @Override
    public void deleteSectionData(long key) {
        connectionPool.withConnection(connection -> {
            try (PreparedStatement preparedStatement = connection.prepareStatement(
                    "delete from section where key = ?"
            )) {
                preparedStatement.setLong(1, key);
                preparedStatement.executeUpdate();
            }
        });
    }

    @Override
    public void putIdMapping(int id, ByteBuffer data) {
        connectionPool.withConnection(connection -> {
            try (PreparedStatement preparedStatement = connection.prepareStatement(
                    "insert into mapping (key, data) values (?, ?) on conflict (key) do update set data = excluded.data"
            )) {
                preparedStatement.setInt(1, id);
                preparedStatement.setBinaryStream(2, new ByteArrayInputStream(data.array()));
            }
        });
    }

    @Override
    public Int2ObjectOpenHashMap<byte[]> getIdMappingsData() {
        return connectionPool.withConnection(connection -> {
            try (PreparedStatement preparedStatement = connection.prepareStatement("select (key, data) from mapping")) {
                Int2ObjectOpenHashMap<byte[]> mappings = new Int2ObjectOpenHashMap<>();
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    mappings.put(resultSet.getInt("key"), resultSet.getBytes("data"));
                }
                return mappings;
            }
        });
    }

    @Override
    public void flush() {
        // AFAICT this is a noop for Postgres
    }

    @Override
    public void close() {
        this.connectionPool.close();
    }

    public static class Config extends StorageConfig {
        @Override
        public StorageBackend build(ConfigBuildCtx ctx) {
            return new RocksDBStorageBackend(ctx.ensurePathExists(ctx.substituteString(ctx.resolvePath())));
        }

        public static String getConfigTypeName() {
            return "PostgreSQL";
        }
    }
}
